### ISSUE TITLE
Feature Request: AR Mode

### ISSUE THREAD

**Issue by kitchWWW** [meta-quest/immersive-web-emulator#1]
Hello!

This tool looks awesome! When I'm playing around with it, I see that it supports the WebXR "VR" features, but it doesn't have support for AR. Would it be possible to enable this? Maybe by providing a default "pass through" image of the user's surroundings? (As I say this, I'm thinking that there would probably need to be spatial anchors, "plane detectors", etc. which would make this significantly more complicated, especially to be as customizable as the rest of the browser extension appears to be.)

<img width="1792" alt="Screen Shot 2022-10-06 at 10 08 30 PM" src="https://user-images.githubusercontent.com/6325818/194452298-0c35f55c-5de8-4955-ace0-a5b50ebef2f3.png">

> Would be nice to not have "AR NOT FOUND"

**Comment by slambo311** [comment]
The regular WebXR emulator already has an AR mode.

**Comment by felixtrz** [comment]
On my list! Not sure when I will get to it though, late this year, early next year?

**Comment by danburonline** [comment]
@felixtrz Would love AR mode since using the other WebXR extension is horrible! Let me know if I can help

**Comment by felixtrz** [comment]
> @felixtrz Would love AR mode since using the other WebXR extension is horrible! Let me know if I can help

Thank you for the offer! I am currently working on it as my top priority. I can definitely use your feedback once the first version of this comes out, and I will definitely welcome PRs that build on top of that!

**Comment by felixtrz** [comment]
We have released AR support in https://github.com/meta-quest/immersive-web-emulator/releases/tag/v1.1.0 , with features like plane-detection and anchor support that are not available in Mozilla's emulator. More details here: https://developer.oculus.com/blog/immersive-web-emulator-1-1/
