### ISSUE TITLE
gamepad axes are undefined

### ISSUE THREAD

**Issue by andreasplesch** [meta-quest/immersive-web-emulator#13]
xrFrame.session.inputSources[n].gamepad.axes[0] can be `undefined` even though the gamepad object exists and is not null.

This apparently happens for the Quest Pro emulator, perhaps as a result of using a polyfill.

The Mozilla extension reports a number as required by the gamepad spec.

**Comment by felixtrz** [comment]
According to the WebXR Gamepad API spec: https://www.w3.org/TR/webxr-gamepads-module-1/#example-mappings,
gamepad.axes[0] and gamepad.axes[1] are supposed to be the x and y value of touch pad on controllers, quest devices do not have a touch pad, so the value being null or undefined is expected.

If you are looking for the joystick x and y value, they are gamepad.axes[2] and gamepad.axes[3]

**Comment by felixtrz** [comment]
Also, according to the spec: https://www.w3.org/TR/webxr-gamepads-module-1/#xr-standard-heading, none of the axes values are required.
<img width="378" alt="Screenshot 2023-02-16 at 3 39 25 PM" src="https://user-images.githubusercontent.com/11973041/219512513-9d7ea7e0-f4f6-4ea9-8350-b507cf135571.png">

**Comment by felixtrz** [comment]
@andreasplesch I am closing this issue now, feel free to reopen this if my comments did not fully address your concerns.

**Comment by andreasplesch** [comment]
Thanks. But I think you missed

https://www.w3.org/TR/webxr-gamepads-module-1/#xr-standard-heading

> Devices that lack one of the optional inputs listed in the tables above MUST preserve their place in the [buttons](https://www.w3.org/TR/gamepad/#dom-gamepad-buttons) or [axes](https://www.w3.org/TR/gamepad/#dom-gamepad-axes) array, reporting a [placeholder button](https://www.w3.org/TR/webxr-gamepads-module-1/#placeholder-button) or [placeholder axis](https://www.w3.org/TR/webxr-gamepads-module-1/#placeholder-axis), respectively. A placeholder button MUST report 0 for [value](https://www.w3.org/TR/gamepad/#dom-gamepadbutton-value), false for [pressed](https://www.w3.org/TR/gamepad/#dom-gamepadbutton-pressed), and false for [touched](https://www.w3.org/TR/gamepad/#dom-gamepadbutton-touched). A placeholder axis MUST report 0.

So instead of null or undefined the placeholder value must be 0.

This is to make it compatible with

https://w3c.github.io/gamepad/#dom-gamepad-axes

which states:

`All axis values MUST be linearly normalized to the range [-1.0 .. 1.0].`

as well as https://www.w3.org/TR/gamepad/#dfn-axes

`A [sequence](https://webidl.spec.whatwg.org/#idl-sequence) of [double](https://webidl.spec.whatwg.org/#idl-double) values representing the current state of axes exposed by this device`

**Comment by andreasplesch** [comment]
Unfortunately I cannot reopen the issue. Please let me know if I should file a new issue.

**Comment by felixtrz** [comment]
Oops! You got me there. I will put up a fix soon!

**Comment by andreasplesch** [comment]
Glad to help !

**Comment by felixtrz** [comment]
This should now be fixed, you can get the fix now by building from source, or you can wait til next week when we push an update. Thanks again for flagging this!
