### ISSUE TITLE
Not Enough Vertical Space

### ISSUE THREAD

**Issue by torugor** [meta-quest/immersive-web-emulator#19]
![image](https://user-images.githubusercontent.com/5396343/231563398-4fb4a443-146e-456d-9973-6b11b9473f35.png)
I go to my VR website, click on open vr and it gives this message not enough vertical space.
Tried to change the window size but didnt work.
No clue how to make this work 
Chrome version 111.0.5563.148

**Comment by felixtrz** [comment]
> ![image](https://user-images.githubusercontent.com/5396343/231563398-4fb4a443-146e-456d-9973-6b11b9473f35.png) I go to my VR website, click on open vr and it gives this message not enough vertical space. Tried to change the window size but didnt work. No clue how to make this work Chrome version 111.0.5563.148

Hey @torugor , you can click on the emulator portion of the dev tools panel, and zoom out until the not enough space warning goes away. I believe the shortcut on mac is cmd -/+, not sure about windows, I assume it's ctrl -/+

**Comment by felixtrz** [comment]
In v1.3 (just released), the minimum size requirement of the emulator panel is 23% of what it used to be, the controller panels will automatically fold if there is not enough space. It should show up now even if you don't zoom. Closing issue.
