### ISSUE TITLE
Panel no longer appears

### ISSUE THREAD

**Issue by mrdoob** [meta-quest/immersive-web-emulator#21]
For some reason the devtools panel no longer appears.

https://threejs.org/examples/webxr_xr_dragging

<img width="1296" alt="Screenshot 2023-05-08 at 19 17 16" src="https://user-images.githubusercontent.com/97088/236799120-ddf577f8-e38f-4bea-84fd-930c208d5529.png">

Sometimes it does appear but it's all white.

<img width="1136" alt="Screenshot 2023-05-08 at 19 09 41" src="https://user-images.githubusercontent.com/97088/236797576-beb544de-01b0-4b48-bfe2-584fdd6b1111.png">

And when it appears and it shows the controls, changing then doesn't affect the app anymore.

Seems like something got pretty unstable... I fear it may be a collision of multiple instances of three.js in memory...?

**Comment by felixtrz** [comment]
This is quite unusual.. may I ask what version of the emulator are you using? I double checked the latest version - v1.2 on the latest Chrome just now, and it seems to work reliably for me. 

It's unlikely to have something to do with the multiple threejs instances - the multiple threejs instances exist in the web page being inspected, not in the WebXR dev tools panel, which will only have one threejs instance for rendering the 3D viewport. Even if something goes wrong in the main web page it shouldn't stop the dev tool page from loading.

One possibility is that this extension is clashing with Mozilla's WebXR API extension, if you have it installed as well, this is known to cause problems, and we generally recommend uninstalling or disabling the older extension if you are using the Immersive Web Emulator.

Another possibility is that this is a local installation and the source files for the emulator are relocated somehow..

If that also doesn't work, can you inspect the devtool panel and the service worker of the extension and see if there are any error messages?

<img width="755" alt="Screenshot 2023-05-08 at 7 59 17 AM" src="https://user-images.githubusercontent.com/11973041/236858692-cac249e3-d821-4436-beaf-487b47877fb3.png">

**Comment by mrdoob** [comment]
It was v1.2.0 yes, and Mozilla's WebXR extension was disabled at the time.

Now I can't reproduce in a different computer.

**Comment by mrdoob** [comment]
However, I'm getting weird stuff like this:

![Screenshot 2023-05-09 at 4 43 08 PM](https://user-images.githubusercontent.com/97088/237029166-acef97ea-1c98-411a-bda9-57e27babe4dd.png)

The debug grid in the extension editor renders in my app too.

**Comment by mrdoob** [comment]
Okay, I've figured out that the debug grid from the extension editor renders in my app when there's a bug in my code 😵‍💫

**Comment by felixtrz** [comment]
> Okay, I've figured out that the debug grid from the extension editor renders in my app when there's a bug in my code 😵‍💫

Hey @mrdoob , v1.3 was released recently, can you verify whether this issue still exists? Thanks!

**Comment by felixtrz** [comment]
I assume this is no longer happening since @mrdoob recently contributed a PR to a later version of IWE, closing issue.
