### ISSUE TITLE
requestHitTestSource doesn't check for feature request

### ISSUE THREAD

**Issue by De-Panther** [meta-quest/immersive-web-emulator#24]
The `XRSession` functions `requestHitTestSource` and `requestHitTestSourceForTransientInput` are not checking if the `hit-test` feature was requested.
As described in the specs
https://www.w3.org/TR/webxr-hit-test-1/#requesting-hit-test
"If hit-test feature descriptor is not contained in the session’s list of enabled features, reject promise with NotSupportedError and abort these steps."

**Comment by felixtrz** [comment]
Good find, will fix in v1.4

**Comment by felixtrz** [comment]
This should have been fixed in v1.3.1
