### ISSUE TITLE
Connection Status is missed (gamepad.connected == undefined)

### ISSUE THREAD

**Issue by eugenner** [meta-quest/immersive-web-emulator#28]
EmulatedXRDevice.gamepads objects have no "connected" property.
After entering in VR mode, <XRRemappedGamepad> gamepad has property "connected" = undefined.
Modules that depend on this status may not work correctly.

**Comment by felixtrz** [comment]
The fix has been landed into the main branch. If you'd like immediate access, you can build from the source to obtain the patch. Otherwise, it will be included in the upcoming v1.4.2 release.

Thank you for bringing this issue to our attention.
