### ISSUE TITLE
XRSession missing enabledFeatures property

### ISSUE THREAD

**Issue by AdaRoseCannon** [meta-quest/immersive-web-emulator#30]
Details: https://immersive-web.github.io/webxr/#dom-xrsession-enabledfeatures

**Comment by felixtrz** [comment]
The fix has been landed into the main branch. If you'd like immediate access, you can build from the source to obtain the patch. Otherwise, it will be included in the upcoming **v1.4.2** release.

Thank you for bringing this issue to our attention.

**Comment by AdaRoseCannon** [comment]
Thank you!On 12 Jan 2024, at 00:34, Felix Z ***@***.***> wrote:﻿
Closed #30 as completed.
