### ISSUE TITLE
Bug: Hands are enabled on sessions with no hand_tracking

### ISSUE THREAD

**Issue by De-Panther** [meta-quest/immersive-web-emulator#33]
On this demo https://de-panther.github.io/WebXR-Unity-Samples/VR/WebXR-Quick-VR/Build/
The `hand_tracking` feature is not requested, but they are displayed when using the emulator in hands mode.
![image](https://github.com/meta-quest/immersive-web-emulator/assets/4749703/1023f1bd-61dd-4f28-a1e2-14be09e24c6b)

**Comment by felixtrz** [comment]
Great catch, I will fix it

**Comment by felixtrz** [comment]
The fix has been landed into the main branch. If you'd like immediate access, you can build from the source to obtain the patch. Otherwise, it will be included in the upcoming **v1.4.2** release.

Thank you for bringing this issue to our attention.
