### ISSUE TITLE
Type in controllers / headset position and rotation

### ISSUE THREAD

**Issue by dmarcos** [meta-quest/immersive-web-emulator#51]
Sometimes for testing one wanna try precise values.

<img width="150" alt="Screenshot 2023-11-24 at 10 32 34 PM" src="https://github.com/meta-quest/immersive-web-emulator/assets/39342/06eaaac2-f800-4b23-8120-d1f1bbcc15c8">

**Comment by felixtrz** [comment]
shipped in v1.5
