### ISSUE TITLE
Error in the chrome extension manager

### ISSUE THREAD

**Issue by parthranawat** [meta-quest/immersive-web-emulator#6]
This is the error I get when I tried to run a WebXR sample from this link-
https://immersive-web.github.io/webxr-samples/inline-session.html

Can someone help me understand what is causing this?

<img width="684" alt="image" src="https://user-images.githubusercontent.com/66198000/211098549-0a40b17c-d3eb-40ec-90e8-e8586ec4a7c0.png">

**Comment by felixtrz** [comment]
AFAIK this error is what you get when you install/refresh your version of the emulator when you have an emulator page open. You can clear the error logs and this shouldn't appear again when you relaunch the experience page with emulator. As for why some WebXR experiences on the immersive-web GitHub repo are not working with the emulator at the moment, I don't have a clue either... I will put in some time next week to investigate, but my guess is that the WebXR polyfill that was injected into the experience by the emulator is conflicting in some way with the built-in WebXR polyfill of those samples. The emulator continue to work with experiences that do not have WebXR polyfill built in, for example: https://sndbx.elixrjs.io

**Comment by felixtrz** [comment]
The latest version is verified to work with https://immersive-web.github.io/webxr-samples/inline-session.html with no error message.
